Simpleperf: remove dependency on global current_arch.
When running unit tests on arm64 devices:
[OK] ReportCommandTest.dwarf_callgraph
[OK] record_cmd.dwarf_callchain_sampling.
ERROR: can't unwind data recorded on a different architecture.

It is because ReportCommandtest.dwarf_callgraph opens a perf.data
recorded on x86_64, and changes current_arch. It makes the following
test record_cmd.dwarf_callchain_sampling can't call libbacktrace built
on aarch64. Although it doesn't make test fail, we should fix this.

Change-Id: I2cd70369a769ef2199cab2302b8b824369be0907